name: Docker deploy

# on:
#   push:
#     branches: [main]
#     paths:
#       - "app.py"
#       - "db_connection.py"
#       - "requirements.txt"
#       - "dockerfile"
#       - "templates/**"
#       - "nginx/**"

on:
  workflow_dispatch:


jobs:
  docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
# Inloggen in ECR in AWS
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 \
          | docker login --username AWS --password-stdin 050670385147.dkr.ecr.eu-central-1.amazonaws.com
# Bouwen van Docker image lokaal
      - name: Build Docker image
        run: |
          docker build -t container_registry:latest .
# Geven van tag aan Docker image
      - name: Tag Docker image
        run: |
          docker tag container_registry:latest 050670385147.dkr.ecr.eu-central-1.amazonaws.com/container_registry:latest
# Pushen van Docker image naar ECR
      - name: Push Docker image to ECR
        run: |
          docker push 050670385147.dkr.ecr.eu-central-1.amazonaws.com/container_registry:latest

# Verkrijgen van de rollout status en triggeren van de rolling update
      - name: Trigger ASG Instance Refresh
        id: refresh
        run: |
          echo "Starting Rolling Instance Refresh for webserver-asg..."
          
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name webserver-asg \
            --strategy Rolling \
            --preferences '{
              "MinHealthyPercentage": 50,
              "InstanceWarmup": 60,
              "SkipMatching": false
            }'
          echo "Deployment succesvol getriggerd in AWS!"